### ISSUE TITLE
"Floating point numbers are not allowedin smart contracts." doesn't give source location

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/assemblyscript#78]
```
[01:23:00] Error: Floating point numbers are not allowedin smart contracts.
    at /Users/vg/Documents/crypto-corgis-solution/node_modules/near-assemblyscript/cli/asc.js:529:15
    at measure (/Users/vg/Documents/crypto-corgis-solution/node_modules/near-assemblyscript/cli/asc.js:853:3)
    at main (/Users/vg/Documents/crypto-corgis-solution/node_modules/near-assemblyscript/cli/asc.js:526:26)
    at Object.main (/Users/vg/Documents/crypto-corgis-solution/node_modules/near-shell/gulp-utils.js:43:16)
    at Object.compile (/Users/vg/Documents/crypto-corgis-solution/node_modules/near-shell/gulp-utils.js:14:9)
    at build_wasm (/Users/vg/Documents/crypto-corgis-solution/gulpfile.js:5:13)
    at bound (domain.js:420:14)
    at runBound (domain.js:433:12)
    at asyncRunner (/Users/vg/Documents/crypto-corgis-solution/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

**Comment by willemneal** [comment]
Ah yes this is due to the fact that it checks for floats at the end.  I can fix it.  This issue should be in the near-bindgen-as repo.
